version: "3"
services:
  mongo:
    container_name: mongo
    image: mongo:4.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_DATA_DIR=/data/db
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
      
volumes:
  db-data: